[package]
name = "sim-server"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
axum.workspace = true
futures-util.workspace = true
hl-wire.workspace = true
oracle-hyperliquid.workspace = true
serde.workspace = true
serde_json.workspace = true
sim-core.workspace = true
tokio.workspace = true
tower.workspace = true
tower-http.workspace = true
url = "2"

[dev-dependencies]
http-body-util.workspace = true
tokio-tungstenite.workspace = true
